Sustainable Gardening Community/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Sustainable_Gardening_Community.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Sustainable Gardening Community/Controllers/TipsController.cs
using AuthSystem.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Sustainable_Gardening_Community.Dtos;
using Sustainable_Gardening_Community.Models;

namespace Sustainable_Gardening_Community.Controllers
{
    public class TipsController : Controller
    {
        private readonly AuthDbContext _context;
        private readonly IWebHostEnvironment _he;
        public TipsController(AuthDbContext context, IWebHostEnvironment he)
        {
            this._context = context;
            this._he = he;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Tips.ToListAsync());
        }

        [Authorize]
        public async Task<IActionResult> ManageTips()
        {
            return View(await _context.Tips.ToListAsync());
        }
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TipsDto tipsDto)
        {
            if (ModelState.IsValid)
            {
                Tips tips = new Tips()
                {
                    Title = tipsDto.Title,
                    Description = tipsDto.Description
                };

                //image
                var file = tipsDto.ImagePath;
                string webroot = _he.WebRootPath;
                string folder = "img";
                string imgFileName = Path.GetFileName(tipsDto.ImagePath.FileName);
                string fileToSave = Path.Combine(webroot, folder, imgFileName);

                if (file != null)
                {
                    using (var stream = new FileStream(fileToSave, FileMode.Create))
                    {
                        tipsDto.ImagePath.CopyTo(stream);
                        tips.Image = "/" + folder + "/" + imgFileName;
                    }
                }


                _context.Tips.Add(tips);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ManageTips));
            }
            return View();
        }

        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            var tips = await _context.Tips.FirstOrDefaultAsync(x => x.Id == id);
            TipsDto tipsDto = new TipsDto()
            {
                Id = tips.Id,
                Title = tips.Title,
                Description = tips.Description,
                Image = tips.Image,
            };


            return View(tipsDto);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(TipsDto tipsDto)
        {
            if (ModelState.IsValid)
            {
                Tips tips = new Tips()
                {
                    Id = tipsDto.Id,
                    Title = tipsDto.Title,
                    Description = tipsDto.Description,
                    Image = tipsDto.Image
                };

                //for image
                var file = tipsDto.ImagePath;
                if (file != null)
                {
                    string webroot = _he.WebRootPath;
                    string folder = "img";
                    string imgFileName = Path.GetFileName(tipsDto.ImagePath.FileName);
                    string fileToSave = Path.Combine(webroot, folder, imgFileName);
                    using (var stream = new FileStream(fileToSave, FileMode.Create))
                    {
                        tipsDto.ImagePath.CopyTo(stream);
                        tipsDto.Image = "/" + folder + "/" + imgFileName;
                    }
                }

                _context.Update(tips);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ManageTips));
            }
            return View();
        }

        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            var tips = await _context.Tips.FirstOrDefaultAsync(x => x.Id == id);
            TipsDto tipsDto = new TipsDto()
            {
                Id = tips.Id,
                Title = tips.Title,
                Description = tips.Description,
                Image = tips.Image,
            };


            return View(tipsDto);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            Tips tips = _context.Tips.Find(id);

            if (tips == null)
            {
                return NotFound();
            }
            _context.Entry(tips).State = EntityState.Deleted;
            _context.SaveChanges();

            return RedirectToAction(nameof(ManageTips));
        }
    }
}

Sustainable Gardening Community/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using AuthSystem.Areas.Identity.Data

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sustainable Gardening Community</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AuthSystem.styles.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
    <link href="~/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jost:wght@500;600;700&family=Open+Sans:wght@400;500&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/lib/lightbox/css/lightbox.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <div class="container">
            <div class="container-fluid bg-dark text-light px-0 py-2">
                <div class="row gx-0 d-none d-lg-flex">
                    <div class="col-lg-7 px-5 text-start">
                        <div class="h-100 d-inline-flex align-items-center me-4">
                            <span class="fa fa-phone-alt me-2"></span>
                            <span>+880 1766750701</span>
                        </div>
                        <div class="h-100 d-inline-flex align-items-center">
                            <span class="far fa-envelope me-2"></span>
                            <span>khairuzzamanrakib153@gmail.com</span>
                        </div>
                    </div>
                    <div class="col-lg-5 text-end">
                        <div class="h-100 d-inline-flex align-items-center mx-n2">
                            @* <span>Follow Us:</span>
                            <a class="btn btn-link text-light" href=""><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-link text-light" href=""><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-link text-light" href=""><i class="fab fa-linkedin-in"></i></a>
                            <a class="btn btn-link text-light" href=""><i class="fab fa-instagram"></i></a> *@
                            @if (SignInManager.IsSignedIn(User)) {
                                <a id="manage" class="nav-link text-light" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @UserManager.GetUserName(User)!</a>
                            }
                        </div>
                        @* <partial name="_LoginPartial.cshtml"/> *@
                    </div>
                </div>
            </div>
            <!-- Topbar End -->
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top p-0">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
                    <h1 class="m-0">Gardener</h1>
                </a>
                <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto p-4 p-lg-0">
                        <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-item nav-link">Home</a>
                        <a asp-area="" asp-controller="About" asp-action="Index" class="nav-item nav-link">About</a>
                        <a asp-area="" asp-controller="Tips" asp-action="Index" class="nav-item nav-link">Tips</a>
                        @* <a href="project.html" class="nav-item nav-link">Projects</a> *@

                        @if (SignInManager.IsSignedIn(User)) {
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Admin</a>
                                <div class="dropdown-menu bg-light m-0">
                                    <a asp-area="" asp-controller="Tips" asp-action="ManageTips" class="dropdown-item">Manage Tips</a>
                                    @* <a href="quote.html" class="dropdown-item">Plant Tracking</a> *@
                                </div>
                            </div>
                        }
                        @* <a href="contact.html" class="nav-item nav-link">Contact</a> *@
                        <partial name="_LoginPartial.cshtml" />
                    </div>
                </div>
            </nav>
        </div>
        @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SGC</a>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Features</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Pricing</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#">Disabled</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav> *@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">

            <!-- Footer Start -->
            <div class="container-fluid bg-dark text-light footer py-5 wow fadeIn" data-wow-delay="0.1s">
                <div class="container py-5">
                    <div class="row g-5">
                        <div class="col-lg-3 col-md-6">
                            <h4 class="text-white mb-4">Our Office</h4>
                            <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>Gulshan 2</p>
                            <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+880 1766750701</p>
                            <p class="mb-2"><i class="fa fa-envelope me-3"></i>khairuzzamanrakib153@gmail.com</p>
                            <div class="d-flex pt-2">
                                <a class="btn btn-square btn-outline-light rounded-circle me-2" href=""><i class="fab fa-twitter"></i></a>
                                <a class="btn btn-square btn-outline-light rounded-circle me-2" href=""><i class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-square btn-outline-light rounded-circle me-2" href=""><i class="fab fa-youtube"></i></a>
                                <a class="btn btn-square btn-outline-light rounded-circle me-2" href=""><i class="fab fa-linkedin-in"></i></a>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6">
                            <h4 class="text-white mb-4">Services</h4>
                            <a class="btn btn-link" href="">Landscaping</a>
                            <a class="btn btn-link" href="">Pruning plants</a>
                            <a class="btn btn-link" href="">Urban Gardening</a>
                            <a class="btn btn-link" href="">Garden Maintenance</a>
                            <a class="btn btn-link" href="">Green Technology</a>
                        </div>
                        <div class="col-lg-3 col-md-6">
                            <h4 class="text-white mb-4">Quick Links</h4>
                            <a class="btn btn-link" href="">About Us</a>
                            <a class="btn btn-link" href="">Contact Us</a>
                            <a class="btn btn-link" href="">Our Services</a>
                            <a class="btn btn-link" href="">Terms & Condition</a>
                            <a class="btn btn-link" href="">Support</a>
                        </div>
                        <div class="col-lg-3 col-md-6">
                            <h4 class="text-white mb-4">Newsletter</h4>
                            <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                            <div class="position-relative w-100">
                                <input class="form-control bg-light border-light w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                                <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->
            <!-- Copyright Start -->
            <div class="container-fluid copyright py-4">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-md-0">
                            &copy; <a class="border-bottom" href="#">Sustainable Gardening Community</a>, All Right Reserved.
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                        Designed and Developed By <a class="border-bottom" href="https://github.com/MDKhairuzzamanRakib">Khairuzzaman</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Copyright End -->
            <!-- Back to Top -->
            <a href="#" class="btn btn-lg btn-primary btn-lg-square rounded-circle back-to-top"><i class="bi bi-arrow-up"></i></a>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/wow/wow.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/lib/counterup/counterup.min.js"></script>
    <script src="~/lib/parallax/parallax.min.js"></script>
    <script src="~/lib/isotope/isotope.pkgd.min.js"></script>
    <script src="~/lib/lightbox/js/lightbox.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>